security.protocol=SASL_SSL
ssl.truststore.location=/home/dthibau/Formations/Kafka/kafka-solutions/ssl/mount/kafka.truststore.jks
ssl.truststore.password=secret
ssl.endpoint.identification.algorithm=

sasl.mechanism=OAUTHBEARER
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
sasl.oauthbearer.token.endpoint.url=http://localhost:9090/realms/kafka/protocol/openid-connect/token

# Nouveau format Kafka 4.x (remplace les options du JAAS)
sasl.oauthbearer.client.credentials.client.id=kafka-producer-client
sasl.oauthbearer.client.credentials.client.secret=producer-secret
sasl.oauthbearer.scope=openid
sasl.oauthbearer.sub.claim.name=azp